### ISSUE TITLE
The formatting marks for formatted links are appended to the link if formatting is applied before the link

### ISSUE THREAD

**Issue by jktoole** [turnermm/ckgedit#255]
If you make some text bold or italic, then make it a link (it doesn't matter if you leave the text selected or deselect and reselect it), the trailing formatting marks are appended to the link text when the document is saved, e.g:

`This sentence also has a **[[:start|bold link**]]** in it.`

..or:

`This sentence has an //[[:start|italicised link//]]// in it.`

In the default editor, formatted text inside a link is left unprocessed, so the first example would look like:

`This sentence has a [[start|**bold link**]] in it.`

**Comment by turnermm** [comment]
Should be fixed in latest master.

**Comment by turnermm** [comment]
Probably fixed in issue 254

**Comment by jktoole** [comment]
Thank you for fixing #254 (and for all your other work on CKGEdit/CKGDoku!), that works perfectly.

Am still seeing this one after updating to the latest version.

**Comment by turnermm** [comment]
`This sentence has a [[start|**bold link**]] in it.`
Can't do that.  But if you want to format a link you can do this, using native Dokuwiki syntax:
**// [[:playground:fonts|start]] // **
The ckgeditor understands the syntax and will format it correctly on saving.  You can also do this:
1. Start with formats:
** //  //**
2. Using the link dialog, insert link between them:
   ** // ` inserted-link` //**

But don't first create the link and then add the formatting markup.  That confuses the editor.
