### ISSUE TITLE
Bullets problem

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#298]
When I use Bullets in my article ,there have some problem.

I use bullets to list data example
- layer1(this will close by a hyperlink)
--layer2
---layer3
![01](https://cloud.githubusercontent.com/assets/10329643/26196778/91f3601c-3bf2-11e7-9c1f-2338ce157058.JPG)

after submitting
the result becomes following
- layer1 *layer2
--layer3
![02](https://cloud.githubusercontent.com/assets/10329643/26196780/944948cc-3bf2-11e7-9eac-6ed8e923c576.JPG)

**Comment by turnermm** [comment]
Please attach a copy of the Dokuwiki text file where this occurs.

**Comment by turnermm** [comment]
Try this: https://github.com/turnermm/ckgedit/archive/listlink.zip
And please let me know if it is working properly for you.

**Comment by qwe852147** [comment]
It does not work.
I just type 
![002](https://cloud.githubusercontent.com/assets/10329643/26289279/44293f96-3ed1-11e7-85a5-7a2aa16fe9c0.JPG)

then it auto turn to this
![003](https://cloud.githubusercontent.com/assets/10329643/26289287/58c2eb00-3ed1-11e7-89f2-1a14e74a2636.JPG)

**Comment by turnermm** [comment]
http://www.youtube.com/watch?v=v3LCKJoauSU

What browser are you using? The video is from firefox, but it works as well in Chrome.

**Comment by turnermm** [comment]
https://www.youtube.com/watch?v=3usfdLhOJqg

**Comment by qwe852147** [comment]
I use Chrome(58.0.3029.110) ,and use the latest version ckeditor 
![yy](https://cloud.githubusercontent.com/assets/10329643/26333321/4a55356e-3f8f-11e7-8077-72dc61e85f8b.JPG)

https://youtu.be/r67bXWl7SHw

**Comment by turnermm** [comment]
You have not answered my questions.  Unless I can repropduce the problem I can't do anything about it.  As far as I can see, on Latin keyboards with  Firefox, Chrome, and Safari, this problem is solved.

**Comment by qwe852147** [comment]
I have installed the listlink.zip which you give but it's still broken.
Any information I should provide?

**Comment by qwe852147** [comment]
Thanks !I found the problem , some plugin influence it.
I will find out .

Sorry...waste your time

**Comment by turnermm** [comment]
You didn't waste my time.  There was a bug and as far as I can see it is now fixed.
