### ISSUE TITLE
Editing page which contains <del> inside table cell may corrupts the page

### ISSUE THREAD

**Issue by orangain** [turnermm/ckgedit#360]
Recently, I've upgraded the ckgedit plugin and found this issue.

## Environment

* DokuWiki: 2017-02-19e
* ckgedit: latest master db02a93518bbff4f899f1fc1d2a59f16f1e9e080
* Browser: Google Chrome 62.0.3202.94

## How to reproduce

1. Install ckgedit plugin into DokuWiki.

2. Click `Edit this page` button of some page (e.g. playground).

3. Click `DW Edit` button, then click `Edit this page` button again.

4. Enter the following source and save it.

   ```
   ====== PlayGround ======
   
   [[http://example.com]]
   
   |<del>10</del>| |
   
   [[http://example.com]]
   ```

   You will see like this as expected:

   <img width="601" alt="2017-12-19 21 51 19" src="https://user-images.githubusercontent.com/532251/34159366-61268478-e50c-11e7-92fc-d449b1a370cc.png">

5. Click `Edit this page` button and click `CKG Edit`.

6. Click `Edit this page` button again.

   You will see like this as NOT expected:

   <img width="600" alt="2017-12-19 21 53 30" src="https://user-images.githubusercontent.com/532251/34159350-4db884a4-e50c-11e7-9a6b-517e6b1161f6.png">

   The problem here is:

   * The second link and the second table cell disappear.
   * Unexpected strings `oIWIKIo` and `cIWIKIc`, that are not included in the source, appear.

7. Click Save.

   You will see that the second link and the second table cell disappear:

   <img width="602" alt="2017-12-19 22 04 09" src="https://user-images.githubusercontent.com/532251/34159425-99ce29b6-e50c-11e7-9116-08de2907761a.png">

**Comment by turnermm** [comment]
Should be fixed in latest update.

**Comment by orangain** [comment]
Thank you for the quick fix! The problem has been fixed in the latest version.

**Comment by kerlerm** [comment]
Issue is not fixed for this case: code block flanked with URLs:
Please reopen. Thanks.

https://pastebin.com/hv0yJVZq
