### ISSUE TITLE
Tables: rightclick-contextmenu -> "cell properties" is missing Textalignment options

### ISSUE THREAD

**Issue by unmadu** [turnermm/ckgedit#438]
Hello,

since I updated to the latest Version (as of now, 16.11.2018) there seems to be this feature missing:

1. Rightclick in a table cell
2. Go to "Cell" -> "Cell Properties"
3. Align Text

On the older version(s) I could control the text alignment in that cell/marked cells to left/right/center. 

This is a rather important function since CKGEdit missaligns text in cells from time to time on its own and my users now cant change that alignment.

Greetings and thanks for this great plugin.

**Comment by turnermm** [comment]
Thanks.  This function got accidentally eliminated when I updated to ckeditor 4.10 at the end of October.  It's now fixed.  Just reinstall ckgedit.

**Comment by unmadu** [comment]
Hello,

thanks for quick response. 
I tried it out and the dialogue now appears but sadly doesnt work. 

- I choose the preferred alignment
- Alignment gets put in in Editor-View and shows
--> After saving all alignments in the tables are lost and all are standard-aligned.

I noticed a difference when I check the source-code-view in the Editor:

**This aligment works:**
<td class="rightalign">myText<br />

**This is the alignment your new version puts in:**
<td class="col1" style="text-align: right;">myText</td>

**Comment by turnermm** [comment]
That was result of change in the CKEditor code.  I've fixed it for the ckgedit parser, and it works in my tests.

**Comment by unmadu** [comment]
It still doesnt work. 
I tried it on my main-wiki and even downloaded a fresh DokuWiki USB-Stick-Version, installed only CKGEdit and made a site. Didnt work there aswell.

**Comment by turnermm** [comment]
Sorry about that.  I had forgotten to compress tatableCell.js.unc, so that the original tableCell.js was still there.  I've updated the file and uploaded the compressed version.

**Comment by unmadu** [comment]
No need to apologize :) . It works now.
Thank you for the quick responses and again, for the great plugin.
