### ISSUE TITLE
ckgedit removes backslashes in code blocks

### ISSUE THREAD

**Issue by kerlerm** [turnermm/ckgedit#463]
ckgedit.master (190221) removes backslashes in code and file blocks as well as in normal text. Three consecutive backslashes are reduced to one, four consecutive backslashes are reduced to two.

DW-Code and result here:
https://gist.github.com/kerlerm/bd479492d35fd33497b2df845123e776

Expected behaviour:
ckgedit should at least not modify backslashes in code and file blocks as they may be part of passwords or file paths.

**Comment by turnermm** [comment]
https://github.com/turnermm/ckgedit/archive/cblock_tbl.zip
Please report back.

**Comment by kerlerm** [comment]
Fix leads to duplication of backslashes in code and file blocks:

https://gist.github.com/kerlerm/29e9bc0d921dcbdf821ba6c680a9846d

**Comment by turnermm** [comment]
The fix for multiple line breaks outside of tables and code blocks is %%////%%

**Comment by kerlerm** [comment]
The fix still alters the number of backslashes in code and file blocks. See gist above. I don't think this issue can be closed...

**Comment by turnermm** [comment]
Not in my tests.  That branch was modified several times and is now merged into the master.

**Comment by kerlerm** [comment]
Sorry to persist, but I pulled the latest master.zip, extracted, invalidated cache by touching conf/local.php and made sure the changes you made in commit # 21e42389bfc62fa66031c6c13418986b28d8a17a are really there. When I put multiple backslashes in code and file blocks _inside_ or _outside_ of tables they get multiplied.

I would expect the content of file and code blocks to not be altered - independent of whether they are used inside of tables or outside in normal text flow...

**Comment by turnermm** [comment]
https://github.com/turnermm/ckgedit/archive/cblock_tbl.zip has been updated, not the master.

**Comment by kerlerm** [comment]
Oh - my bad! Thanks for the hint. Now the issue is fixed. Thanks a lot!

**Comment by turnermm** [comment]
cblock_tbl has now been merged int the master and the download branch has now been switched back to master from stable, where is was while I was trying to fix this.

**Comment by Edzilla2000** [comment]
Hello, 
I still have this issue on the latest version of the plugin (2019-04-04)

This is code that gets stripped of backslashes:

> <code>
> PS C:\ldp\2012R2\> import-module .\LDP-SetupManager.psm1
> PS C:\ldp\2012R2\> New-LDPVM -configFile C:\ldp\2012R2\CFG\VMLDP-HyperV-VM.xml
> </code>
>

**Comment by turnermm** [comment]
Not in my tests.

**Comment by Edzilla2000** [comment]
I have other examples, but they are part of a much larger page. I suspect it's the interaction with something else that causes the issue.
Can I send you the page that causes issues? It has some stuff in it that I would rather not see on a github issue page

**Comment by turnermm** [comment]
Sure.  turnermm03 AT shaw.ca

**Comment by Edzilla2000** [comment]
Thank you very much, I have sent you a link to the page just now

**Comment by turnermm** [comment]
Try this: https://github.com/turnermm/ckgedit/archive/cbl_bslash_2.zip

**Comment by turnermm** [comment]
There has been an update to the above at 08:24 CST

**Comment by turnermm** [comment]
This should be fixed and was merged: #480

**Comment by Edzilla2000** [comment]
It is indeed fixed, thank you very much

**Comment by turnermm** [comment]
It took a bit of work because of side effects in the earlier states.  But fixing your issue also led to a more generally correct output.
 
Thanks.

**Comment by kerlerm** [comment]
Unfortunately, the double backslashes get removed in a second file block. Occurs in conjunction with a following link only. 

I tested the master branch with this code:
https://gist.github.com/kerlerm/b4439874b3936d385b71edde7f56b960/raw/5621b7ba0c8707705efccaefb2b41ee02a095c06/dw_code_multi_backslash_3

I know there are hunderts of possible combinations ckgedit has to handle - but could you please have a look at this special situation? Thanks!

**Comment by turnermm** [comment]
Use  `<code>` in stead of `<file>`.  When I have the time I'll check the reason why `file` is not working with double backslashes.

**Comment by turnermm** [comment]
Update you ckgedit, this should be fixed

**Comment by turnermm** [comment]
I did some further work on this, see the latest ckgedit.

**Comment by kerlerm** [comment]
The backslashes are retained now. Thanks!  Unfortunately your latest fixes have some side effect on table layouts:
I have placed code blocks in tables, to store some strings. The latest version of ckgedit destroys these tables by adding newlines:

https://gist.githubusercontent.com/kerlerm/bcae4d5a4c87b0a2cbf4292961893c38/raw/a608c9145b2af3b160d1d77cc11730475171054c/gistfile1.txt

**Comment by turnermm** [comment]
fixed

**Comment by kerlerm** [comment]
Thanks for the fast reaction! This fixes my example but is not an universal fix for the situation "arbitrary code/file blocks in tables".

**Comment by turnermm** [comment]
> "arbitrary code/file blocks in tables".

don't know what this means

**Comment by turnermm** [comment]
Perhaps you meant that tables were broken from more than one block.  I reverted to original code where this did not occur, plus some current updates.  It seems to be ok but if not, I have gone as far as I currently have the patience for, and you will have to use the include plugin if you are not happy with the result.

**Comment by kerlerm** [comment]
Yes, i meant "multiple" code/file blocks in tables. The current master fixes this for me because of your revert. Double backslashes are also kept now. Thanks for your efforts!

**Comment by turnermm** [comment]
This is good to hear.  Thank you for you testing.
