### ISSUE TITLE
Unicode namespaces with internal link dialog

### ISSUE THREAD

**Issue by alibttb** [turnermm/ckgedit#87]
the link dialog has a problem with UNICODE characters in file and folder names on windows platform, and non ASCII characters saved using URL encoding.
the next 4 images explain the problem.
![capture](https://cloud.githubusercontent.com/assets/10291724/7500871/45adeb58-f439-11e4-924a-5de4e9eb5702.PNG)
![capture1](https://cloud.githubusercontent.com/assets/10291724/7501190/03dfc046-f43b-11e4-9c59-1bfe446fce34.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10291724/7501270/7c594a9c-f43b-11e4-8933-3a49570b3933.PNG)
![capture](https://cloud.githubusercontent.com/assets/10291724/7501335/e62368ea-f43b-11e4-87dd-23bfa0e0434a.PNG)

I tried changing other setting for *fnencode* but nothing worked.

on **linux** hosts creating the link works but it have a problem with finding the headings in the advanced tab.

**Comment by turnermm** [comment]
> on linux hosts creating the link works but it have a problem with finding the headings in the advanced tab

Could you be more specific?

**Comment by alibttb** [comment]
it reads the file name correctly, if it's not encoded with URLencode, but any way it cannot resolve the headings in the advanced tab, the combo box always get an empty list after clicking on GetHeadings button.
![capture](https://cloud.githubusercontent.com/assets/10291724/7533331/2e8e81d0-f579-11e4-9ca3-3dfa8120c1dd.PNG)

**to be more specific about the Linux**  the configuration option *fnencode*  is set to *utf-8* instead of *URLencode*.
*hint* Linux uses utf-8 for file names while windows uses utf-16, on the other PHP file system functions doesn't recognize Unicode, I think this explain the part where **Browse Server** button function get the name right on Linux but never on Windows.
If you may point me to the code I should look into I might be able to be more specific about the bug.

Any way, making the code able to understand UrlEncoded file names solvers every thing.

**Comment by turnermm** [comment]
I believe this should be fixed in the latest version.  It does not deal with Windows, only with Linux.

**Comment by alibttb** [comment]
I'll test your latest code on Windows and Linux and I'll give you a feed back.

BTW what do you mean by *It does not deal with Windows, only with Linux.*?

**Comment by alibttb** [comment]
well sir, still having the same encoding problem for folder name (*namespace*) in wiki terms, when browsing the server for the page it gets the name wrong like this:
![capture](https://cloud.githubusercontent.com/assets/10291724/7543835/683bc09e-f5d0-11e4-816e-6e8bf243d6b1.PNG)

any way, if I write the name, it gets the headers right in the advanced tab, so I can say it's almost fixed :)

**Comment by turnermm** [comment]
You are saying:  it does not render the namespace correctly, but it does render the filename correctly.
I am not sure what the source of this error is; it does render correctly in ltr languages.   It's the first time it has been reported.

**Comment by turnermm** [comment]
Since you seem to have some experience with programming, you can look at the function 
``OpenFile( fileUrl )`` in ``ckgedit/fckeditor/editor/filemanager/browser/default/frmresourceslist.html``
For utf8 conversions, you can use the functions in ``default/js/safeFN_class.js``, which the browser files use throughout.  This ``OpenFile()`` function sends the file path to ``ckeditor/plugins/link/dialogs/link.js``, which you can experiment with in the uncompressed format ``link.js.unc``.  Please let me know if you are successful and, if so, what code changes you have made.  You can fork ckgedit and send a pull request.

**Comment by alibttb** [comment]
okay, thank you, I'll try to understand more about it using this information, I'll and will contact you with more details asap.
